const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const html=fs.readFileSync('index.html','utf8');
JSON.parse(fs.readFileSync('manifest.json','utf8'));
for(const file of ['financial-decision-engine.js','norteia-v2.js','norteia-completion.js','service-worker.js','community.js','community-mobile.js'])new vm.Script(fs.readFileSync(file,'utf8'),{filename:file});
const inline=[...html.matchAll(/<script(?![^>]*src)[^>]*>([\s\S]*?)<\/script>/gi)];
inline.forEach((match,index)=>new vm.Script(match[1],{filename:'index-inline-'+index+'.js'}));
const staticHtml=html.replace(/<script[\s\S]*?<\/script>/gi,'');
const ids=[...staticHtml.matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]);
const duplicates=[...new Set(ids.filter((id,index)=>ids.indexOf(id)!==index))];
assert.deepEqual(duplicates,[],'IDs duplicados: '+duplicates.join(', '));
for(const id of ['todayGreeting','todayCommand','todaySafeValue','todayFormula','todayPositiveImpact','todayIgnoreRisk'])assert.ok(html.includes('id="'+id+'"'),id+' ausente');
assert.ok(html.includes('financial-decision-engine.js'),'motor não carregado');
assert.ok(html.includes('norteia-completion.js'),'módulos de conclusão não carregados');
assert.ok(!html.includes('Cockpit'),'a marca antiga ainda aparece na interface principal');
assert.ok(html.includes("localStorage.getItem('norteia_last_user')")&&html.includes("localStorage.removeItem('norteia_last_user')"),'sessão local offline incompleta');
const a11y=fs.readFileSync('norteia-v2.js','utf8'),design=fs.readFileSync('norteia-v2.css','utf8');
assert.ok(a11y.includes("'dashboard','more','community','settings'"),'navegação principal não foi consolidada');
for(const target of ['register','decisions','analysis','projection','plan','wallet','debts','dividends','simulator','weekly'])assert.ok(a11y.includes('data-more-target="'+target+'"'),'função não integrada em Recursos: '+target);
assert.ok(a11y.includes('dashboardExpandBtn'),'controle de detalhes da tela Hoje ausente');
assert.ok(html.includes('mobileExpenseDonut')&&html.includes('mobileInvestmentDonut'),'gráficos essenciais mobile ausentes');
assert.ok(html.includes('mobileSpendToday'),'quanto posso gastar hoje desapareceu do mobile');
assert.ok(html.includes('id="mobilePrivacyBtn"')&&a11y.includes('addMobilePrivacyControl'),'controle de privacidade mobile ausente');
assert.ok(html.includes('id="investmentCreatePanel"')&&html.includes('id="investmentUpdatePanel"')&&a11y.includes('addWalletEditorControls'),'editores compactos da carteira ausentes');
assert.ok(html.includes('freemium.js?v=41')&&html.includes('contrast.css?v=41'),'arquivos críticos sem renovação explícita de cache');
const mobileCommunity=fs.readFileSync('community-mobile.js','utf8'),communityCss=fs.readFileSync('community.css','utf8');
assert.ok(!mobileCommunity.includes('<span>Comunidade Norteia</span>'),'rótulo redundante da comunidade ainda aparece');
assert.ok(!communityCss.includes('#c64200')&&!communityCss.includes('#ff7a38'),'laranja alheio à marca ainda aparece na comunidade');
const brandIcon=fs.readFileSync('assets/brand/norteia-icon.svg','utf8');
assert.ok(brandIcon.includes('#064E42')&&!brandIcon.includes('#0B1D33'),'fundo azul ainda aparece no ícone da marca');
assert.ok(html.includes('norteia-icon.svg?v=39')&&html.includes('apple-touch-icon.png?v=39'),'cache dos ícones não foi renovado');
assert.ok(html.includes('dashboard-command-rail'),'central integrada do desktop ausente');
assert.ok(a11y.includes("event.key==='Escape'")&&a11y.includes("event.key!=='Tab'"),'controle de foco dos modais ausente');
assert.ok(design.includes(':focus-visible'),'foco visível ausente');
console.log('Build estático e integração da tela Hoje: OK');
