const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const html=fs.readFileSync('index.html','utf8');
JSON.parse(fs.readFileSync('manifest.json','utf8'));
for(const file of ['financial-decision-engine.js','norteia-v2.js','norteia-completion.js','service-worker.js','community.js','community-mobile.js'])new vm.Script(fs.readFileSync(file,'utf8'),{filename:file});
const inline=[...html.matchAll(/<script(?![^>]*src)[^>]*>([\s\S]*?)<\/script>/gi)];
inline.forEach((match,index)=>new vm.Script(match[1],{filename:'index-inline-'+index+'.js'}));
const staticHtml=html.replace(/<script[\s\S]*?<\/script>/gi,'');
const ids=[...staticHtml.matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]);
const duplicates=[...new Set(ids.filter((id,index)=>ids.indexOf(id)!==index))];
assert.deepEqual(duplicates,[],'IDs duplicados: '+duplicates.join(', '));
for(const id of ['todayGreeting','todayCommand','todaySafeValue','todayFormula','todayPositiveImpact','todayIgnoreRisk'])assert.ok(html.includes('id="'+id+'"'),id+' ausente');
assert.ok(html.includes('financial-decision-engine.js'),'motor não carregado');
assert.ok(html.includes('norteia-completion.js'),'módulos de conclusão não carregados');
assert.ok(!html.includes('Cockpit'),'a marca antiga ainda aparece na interface principal');
assert.ok(html.includes("localStorage.getItem('norteia_last_user')")&&html.includes("localStorage.removeItem('norteia_last_user')"),'sessão local offline incompleta');
const a11y=fs.readFileSync('norteia-v2.js','utf8'),design=fs.readFileSync('norteia-v2.css','utf8');
assert.ok(a11y.includes("event.key==='Escape'")&&a11y.includes("event.key!=='Tab'"),'controle de foco dos modais ausente');
assert.ok(design.includes(':focus-visible'),'foco visível ausente');
console.log('Build estático e integração da tela Hoje: OK');
